//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegratingGoogleMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int ID { get; set; }
        public decimal AmountDonated { get; set; }
        public System.DateTime DonationDate { get; set; }
        public int CauseID { get; set; }
        public int ConstituentID { get; set; }
    
        public virtual Constituent Constituent { get; set; }
        public virtual Cause Caus { get; set; }
    }
}
