//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegratingGoogleMap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBIndexEntities1 : DbContext
    {
        public BBIndexEntities1()
            : base("name=BBIndexEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cause> Causes { get; set; }
        public DbSet<Constituent> Constituents { get; set; }
        public DbSet<Donation> Donations { get; set; }
    }
}
